import { createGetText } from "../shared/i18nHelpers.js";

export const ANNOUNCEMENT_I18N = {
  en: {
    loadAnnouncementsFailed: "Failed to load announcements: {message}",
    loadMaintenanceFailed: "Failed to load maintenance content: {message}",
    announcementPublishedSuccess: "Announcement published successfully",
    maintenancePublishedSuccess: "Maintenance content published successfully",
    confirmDeleteAnnouncement: 'Are you sure you want to delete announcement "{title}"?\nThis action cannot be undone.',
    confirmDeleteMaintenance: "Are you sure you want to delete this maintenance content?\nThis action cannot be undone.",
    announcementDeletedSuccess: "Announcement deleted successfully",
    maintenanceDeletedSuccess: "Maintenance content deleted successfully",
    deleteFailed: "Delete failed: {message}",
    failedToDelete: "Failed to delete: {message}",
    announcementUpdatedSuccess: "Announcement updated successfully",
    maintenanceUpdatedSuccess: "Maintenance content updated successfully",
    updateFailed: "Update failed: {message}",
    publishFailed: "Publish failed: {message}",
    titleCannotBeEmpty: "Title cannot be empty",
    prefixCannotBeEmpty: "Prefix cannot be empty",
    contentCannotBeEmpty: "Content cannot be empty",
    pageTitle: "Announcement and Maintenance Management",
    announcementTab: "Announcement",
    maintenanceTab: "Maintenance",
    createNewAnnouncement: "Create New Announcement",
    titleRequired: "Title *",
    enterAnnouncementTitle: "Enter announcement title",
    sectionLabelOptional: "List section title (optional)",
    enterSectionLabel: "e.g. ✨ This update includes ✨",
    sectionLabelHint: "Shown above the numbered list on the notification card. Leave empty to use the default.",
    contentRequired: "Content *",
    enterAnnouncementContent: "Enter announcement content",
    publishing: "Publishing...",
    publishAnnouncement: "Publish Announcement",
    publishedAnnouncements: "Published Announcements",
    noAnnouncements: "No announcements",
    edit: "Edit",
    delete: "Delete",
    createdBy: "CREATED BY: {name}",
    createdAt: "CREATED AT: {time}",
    createNewMaintenanceContent: "Create New Maintenance Content",
    prefixRequired: "Prefix *",
    enterMaintenancePrefix: "e.g. System Maintenance:",
    noticeLabel: "Notice",
    maintenanceNotice: "Maintenance content already exists. Please delete the existing content before creating a new one.",
    enterMaintenanceContent: "Enter maintenance content",
    publishMaintenanceContent: "Publish Maintenance Content",
    publishedMaintenanceContent: "Published Maintenance Content",
    noMaintenanceContent: "No maintenance content",
    confirmTitle: "Confirm",
    cancel: "Cancel",
    editAnnouncement: "Edit Announcement",
    close: "Close",
    saveChanges: "Save Changes",
    saving: "Saving...",
    editMaintenanceContent: "Edit Maintenance Content",
    contactTab: "Contact",
    telegramSectionTitle: "Telegram Support Link",
    telegramLinkLabel: "Telegram support link",
    telegramLinkPlaceholder: "YourSupportChannel",
    telegramLinkHint: "Shown as a floating button on the login page. Paste a full t.me link or just the handle — the prefix is filled in for you. Leave empty and save to hide the button.",
    telegramLinkInvalid: "Only letters, numbers, underscore and + are allowed",
    telegramStatusSectionTitle: "Login Page Button Status",
    telegramLinkNotSet: "Not set — button is hidden on the login page",
    saveTelegramLink: "Save",
    telegramLinkSaved: "Telegram link saved successfully",
    currentlyLive: "Currently live",
    testLink: "Test link ↗",
    statusActive: "Active",
    statusHidden: "Hidden",
    updatedBy: "UPDATED BY: {name}",
    updatedAt: "UPDATED AT: {time}",
  },
  zh: {
    loadAnnouncementsFailed: "加载公告失败：{message}",
    loadMaintenanceFailed: "加载维护内容失败：{message}",
    announcementPublishedSuccess: "公告发布成功",
    maintenancePublishedSuccess: "维护内容发布成功",
    confirmDeleteAnnouncement: '确定要删除公告“{title}”吗？\n此操作不可撤销。',
    confirmDeleteMaintenance: "确定要删除此维护内容吗？\n此操作不可撤销。",
    announcementDeletedSuccess: "公告删除成功",
    maintenanceDeletedSuccess: "维护内容删除成功",
    deleteFailed: "删除失败：{message}",
    failedToDelete: "删除失败：{message}",
    announcementUpdatedSuccess: "公告更新成功",
    maintenanceUpdatedSuccess: "维护内容更新成功",
    updateFailed: "更新失败：{message}",
    publishFailed: "发布失败：{message}",
    titleCannotBeEmpty: "标题不能为空",
    prefixCannotBeEmpty: "前缀不能为空",
    contentCannotBeEmpty: "内容不能为空",
    pageTitle: "公告与维护管理",
    announcementTab: "公告",
    maintenanceTab: "维护",
    createNewAnnouncement: "创建新公告",
    titleRequired: "标题 *",
    enterAnnouncementTitle: "请输入公告标题",
    sectionLabelOptional: "列表分区标题（可选）",
    enterSectionLabel: "例如：✨ 本次更新包括 ✨",
    sectionLabelHint: "显示在铃铛通知卡编号列表上方；留空则用默认「本次更新包括」。",
    contentRequired: "内容 *",
    enterAnnouncementContent: "请输入公告内容",
    publishing: "发布中...",
    publishAnnouncement: "发布公告",
    publishedAnnouncements: "已发布公告",
    noAnnouncements: "暂无公告",
    edit: "编辑",
    delete: "删除",
    createdBy: "创建者：{name}",
    createdAt: "创建时间：{time}",
    createNewMaintenanceContent: "创建新维护内容",
    prefixRequired: "前缀 *",
    enterMaintenancePrefix: "例如：系统维护中:",
    noticeLabel: "提示",
    maintenanceNotice: "维护内容已存在，请先删除现有内容后再创建新内容。",
    enterMaintenanceContent: "请输入维护内容",
    publishMaintenanceContent: "发布维护内容",
    publishedMaintenanceContent: "已发布维护内容",
    noMaintenanceContent: "暂无维护内容",
    confirmTitle: "确认",
    cancel: "取消",
    editAnnouncement: "编辑公告",
    close: "关闭",
    saveChanges: "保存更改",
    saving: "保存中...",
    editMaintenanceContent: "编辑维护内容",
    contactTab: "客服",
    telegramSectionTitle: "Telegram 客服链接",
    telegramLinkLabel: "Telegram 客服链接",
    telegramLinkPlaceholder: "YourSupportChannel",
    telegramLinkHint: "将作为悬浮按钮显示在登录页。可以直接粘贴完整的 t.me 链接，或者只填用户名，前缀会自动补上。留空并保存即可隐藏该按钮。",
    telegramLinkInvalid: "只能包含字母、数字、下划线和 +",
    telegramStatusSectionTitle: "登录页按钮状态",
    telegramLinkNotSet: "尚未设置 — 登录页按钮当前处于隐藏状态",
    saveTelegramLink: "保存",
    telegramLinkSaved: "Telegram 链接保存成功",
    currentlyLive: "当前生效",
    testLink: "测试链接 ↗",
    statusActive: "已生效",
    statusHidden: "已隐藏",
    updatedBy: "更新者：{name}",
    updatedAt: "更新时间：{time}",
  },
};

export const getAnnouncementText = createGetText(ANNOUNCEMENT_I18N);
